name: Release

on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Prepare Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          semantic_version: 21

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Finalize Release
        if: success()
        run: echo "Release successful!"