name: Release

on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          - echo $NPM_TOKEN
          - echo $GH_TOKEN
          - npx semantic-release